### ISSUE TITLE
Crash on QHY290

### ISSUE THREAD

**Issue by oleg-milantiev** [emaadparacha/SingleFrame-QHYCCD#1]
Hi!

Thanks for good example.
But have minor issue. My QHY290 cam have no any read mode. Program exit here
>    printf("Could not set read mode. Error: %d. Program will now exit. \n", retVal);

I just comment this block and catch images.
Maybe this method need to be optional like setting temperature (my little camera cant do it too).

**Comment by emaadparacha** [comment]
Ah correct, this is for cameras that have that. I tested it with QHY600, which has that setting. I'll put a comment in the code accordingly!

**Comment by emaadparacha** [comment]
I've updated the code with that commented in and also mentioned in the main README! Hope it worked otherwise!
